config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :merchants do
    get 'map', on: :member
    get 'reviews', on: :member
    put 'update_review', on: :member
  end

  resources :categories, :only => [:map, :show] do
    get 'map', on: :member
  end

  root 'welcome#index'
  get 'search' => 'merchants#search'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :merchants
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :merchants
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base

  belongs_to :category
  belongs_to :location
  has_many :ratings

  reverse_geocoded_by :lat, :lng
  after_validation :reverse_geocode  # auto-fetch address
  geocoded_by :address, :latitude  => :lat, :longitude => :lng   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  def reviews_score
    "*" * [*1..5].sample
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :merchant
  belongs_to :user

  validates_uniqueness_of :user, scope: :merchant
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :ratings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def map
    @category = Category.find(params[:id])
  end

  def show
    @category = Category.find(params[:id])
  end

end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy, :map, :reviews, :update_review]

  # GET /search
  def search
    @selected_category_id = params[:category]
    @selected_location_id = params[:location]
    @merchants = Merchant.where(category_id: params[:category], location_id: params[:location]).take(8).each
    @categories = Category.all
    @locations = Location.all
    render 'search_results'
  end

  # GET /merchants
  # GET /merchants.json
  def index
    @merchants = Merchant.all
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
    @rating = Rating.where(merchant: @merchant, user: @current_user)
    @average = Rating.where(merchant_id: @merchant.id).average(:score)
  end

  # GET /map
  def map
  end

  # GET /merchants/new
  def new
    @merchant = Merchant.new
  end

  # GET /merchants/1/edit
  def edit
  end

  # POST /merchants
  # POST /merchants.json
  def create
    @merchant = Merchant.new(merchant_params)

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to @merchant, notice: 'Merchant was successfully created.' }
        format.json { render :show, status: :created, location: @merchant }
      else
        format.html { render :new }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchants/1
  # PATCH/PUT /merchants/1.json
  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.json
  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to merchants_url, notice: 'Merchant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reviews
    @reviews = Rating.where(merchant_id: @merchant.id)
    @review = Rating.new
  end

  def update_review
    Rating.create(user: current_user, merchant: @merchant, score: params[:score], comment: params[:comment])
    redirect_to reviews_merchant_path(@merchant)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merchant_params
      params.require(:merchant).permit(:name, :address, :lat, :lng, :category, :location, :phone, :website, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @categories = Category.all
    @locations = Location.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/map.html.erb
<div id="map" class="map-category" data-hidden="<%= @category.id %>"></div>

app/views/layouts/_navigation.html.erb
<!-- Want to modify the menu? http://getbootstrap.com/components/#navbar -->
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-brand">
      <a href="/"><span class="glyphicon glyphicon-home"></span>
      <span id="logo">BeautyScanner</span></a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeautyScanner</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div class="container">
    <%= render 'layouts/navigation' %>
    
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>


<%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js' %>
<%= javascript_include_tag '//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry' %>
<%= javascript_include_tag '//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' %>
</body>
</html>

app/views/merchants/_form.html.erb
<%= form_for(@merchant) do |f| %>
  <% if @merchant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

      <ul>
      <% @merchant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/merchants/_form_reviews.html.erb
<%= form_tag(update_review_merchant_path, method: "put") do %>
  <div>
    <%= number_field_tag 'score', nil, in: 1..5, class: 'myButton ratings' %>
    <%= text_field_tag 'comment', value ="Enter your review here...", class: 'form-control review'%>
    <br>
    <br>
    <%= submit_tag "Submit", class: 'myButton' %>
  </div>
<% end %>

app/views/merchants/edit.html.erb
<h1>Editing merchant</h1>

<%= render 'form' %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

app/views/merchants/index.html.erb
<h1>Listing merchants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Category</th>
      <th>Location</th>
      <th>Phone</th>
      <th>Website</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.name %></td>
        <td><%= merchant.address %></td>
        <td><%= merchant.category %></td>
        <td><%= merchant.location %></td>
        <td><%= merchant.phone %></td>
        <td><%= merchant.website %></td>
        <td><%= merchant.email %></td>
        <td><%= link_to 'Show', merchant %></td>
        <td><%= link_to 'Edit', edit_merchant_path(merchant) %></td>
        <td><%= link_to 'Destroy', merchant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Merchant', new_merchant_path %>

app/views/merchants/map.html.erb
<div id="map" class="map-merchant" data-hidden="<%= @merchant.id %>"></div>

<div class="col-md-12 navbar navbar-default">  
  <p><h4>
    <%= @merchant.name %>
  </h4></p>

    <p>
      <%= link_to 'Reviews: ', reviews_merchant_path(@merchant) %>
      <% if @average == nil%>
        <i>No reviews yet</i>
      <% else %>
        <% @average.to_i.times do %>
        <span class="glyphicon glyphicon-star"
        ></span>
        <% end %>

        <% (5-@average).to_i.times do %>
        <span class="glyphicon glyphicon-star-empty"></span>
        <% end %>
      <% end %>
    </p>

  <form class="form-horizontal" role="form">
    <% if @merchant.address? %>
      <div class="form-group">
        <label class="col-xs-2 control-label">
        <span class="glyphicon glyphicon-map-marker"></span></label>
        <div class="col-sm-5">
          <p class="form-control-static"><%= @merchant.address %></p>
        </div>
      </div>
    <% else %>
    <% end %>
    <% if @merchant.phone? %>
      <div class="form-group">
        <label class="col-xs-2 control-label"><span class="glyphicon glyphicon-earphone"></span></label>
        <div class="col-sm-5">
          <p class="form-control-static"><%= @merchant.phone %></p>
        </div>
      </div>
    <% else %>
    <% end %>
    <% if @merchant.website? %>
      <div class="form-group">
        <label class="col-xs-2 control-label"><span class="glyphicon glyphicon-globe"></span></label>
        <div class="col-sm-5">
          <p class="form-control-static"><%= @merchant.website %></p>
        </div>
      </div>
    <% else %>
    <% end %>
  </form>

</div>

app/views/merchants/new.html.erb
<br>
<div type="button" class="btn btn-default" id="add">+ Appointment
</div>
<br>
<br>
<div id = "calendar"></div>
<%= link_to 'Back', merchants_path %>


<script type="text/javascript" src="js/language/xx-XX.js"></script>
<%= stylesheet_link_tag "application-print", :media => "print" %>

app/views/merchants/reviews.html.erb
<h4><%= @merchant.name %> reviews:<h4>
<table class="table table-hover">
  <tbody>
    <% @reviews.each do |review| %>
      <tr class="<%= cycle('oddrow', 'evenrow') -%>">
        <td>
          <% if review.score != nil%>
            <%= review.score.to_i.times do %>
              <span class="glyphicon glyphicon-star"
              ></span>
            <% end %>
            <% (5-review.score).to_i.times do %>
              <span class="glyphicon glyphicon-star-empty"></span>
            <% end %>
          <% else %>
          <% end %>
        </td>
        <td><%= review.comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= render 'form_reviews' %>
<br>
<br>
<a href="/merchants/<%= @merchant.id %>">Back to merchant's page</a>

app/views/merchants/search_results.html.erb
<%= form_tag("/search", method: "get") do %>
  
  <%= select_tag 'category', options_from_collection_for_select(@categories,'id', 'name', @selected_category_id), class: 'search btn btn-default btn-lg myButton' %>
  
  <%= select_tag 'location', options_from_collection_for_select(@locations, 'id', 'name', @selected_location_id), class: 'search btn btn-default btn-lg myButton' %>

<% end %>

<table class="table table-hover">
  <tbody>
    <% @merchants.each do |m| %>
      <tr class="<%= cycle('oddrow', 'evenrow') -%>">
        <td><a href="/merchants/<%= m.id %>"><%= m.name %>
        <br><span class="glyphicon glyphicon-map-marker"></span><%= m.address %></td></a>
        <td><a href="/merchants/<%= m.id %>"><br><%= m.reviews_score %></a></td>
      </tr>
    <% end %>
  </tbody>
</table>
<button type="button" class="btn btn-default btn-lg btn-block">
  <%= link_to 'Map view', map_category_path(@selected_category_id) %>
  </button>

app/views/merchants/show.html.erb
<div class="col-md-12 navbar-default showone" data-hidden="<%= @merchant.id %>">
  <button type="button" class="btn btn-default btn-lg btn-block myButton">
    <%= link_to 'Show map', map_merchant_path %>
  </button>
</div>

<div class="col-md-12 navbar navbar-default">  
  <p><h4>
    <%= @merchant.name %>
  </h4></p>

    <p>
      <%= link_to 'Reviews: ', reviews_merchant_path(@merchant) %>
      <% if @average == nil%>
        <i>No reviews yet</i>
      <% else %>
        <% @average.to_i.times do %>
        <span class="glyphicon glyphicon-star"
        ></span>
        <% end %>

        <% (5-@average).to_i.times do %>
        <span class="glyphicon glyphicon-star-empty"></span>
        <% end %>
      <% end %>
    </p>

  <form class="form-horizontal" role="form">
    <% if @merchant.address? %>
      <div class="form-group">
        <label class="col-xs-2 control-label">
        <span class="glyphicon glyphicon-map-marker"></span></label>
        <div class="col-sm-5">
          <p class="form-control-static"><%= @merchant.address %></p>
        </div>
      </div>
    <% else %>
    <% end %>
    <% if @merchant.phone? %>
      <div class="form-group">
        <label class="col-xs-2 control-label"><span class="glyphicon glyphicon-earphone"></span></label>
        <div class="col-sm-5">
          <p class="form-control-static"><%= @merchant.phone %></p>
        </div>
      </div>
    <% else %>
    <% end %>
    <% if @merchant.website? %>
      <div class="form-group">
        <label class="col-xs-2 control-label"><span class="glyphicon glyphicon-globe"></span></label>
        <div class="col-sm-5">
          <p class="form-control-static"><%= @merchant.website %></p>
        </div>
      </div>
    <% else %>
    <% end %>
      <div class="form-group">
        <label class="col-xs-2 control-label"><span class="glyphicon glyphicon-calendar"></span></label>
        <div class="col-sm-5">
          <p class="form-control-static"><%= link_to 'Book Now!', new_merchant_path %></p>
        </div>
      </div>
  </form>

</div>

app/views/welcome/index.html.erb
<%= form_tag("/search", method: "get") do %>
  <div class="homepage">
    <div class="homepage_buttons">
      <%= select_tag 'category', options_from_collection_for_select(@categories, 'id', 'name'), class: 'myButton' %>
    </div>
    <div class="homepage_buttons">
      <%= select_tag 'location', options_from_collection_for_select(@locations, 'id', 'name'), class: 'myButton' %>
    </div>
  </div>

  <div id="findButton"><%= submit_tag("Find", class: 'myButton') %></div>
<% end %>